### ISSUE TITLE
tinymce editor won't clear input

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#349] opened 2019-02-24 01:11 UTC
tried to clear the input after saving to the database however it doesn't seem to work correctly.

See `database-backend` branch and try adding a response to any of the discussions.

**Comment by tx4x** [comment] 2019-02-25 19:52
i think this is because you have an incorrect onChange handler, please check : return indexOf("") == -1 or so is wrong. just make it return true and things should be fine for now.

**Comment by tx4x** [comment] 2019-02-25 19:52
will check my self as well.

**Comment by chrismclarke** [comment] 2019-02-26 00:10
So in `pages/discussions/postView/index.ts` the onChange handler is set to just return true, and when I log the state it says content should be "" but the editor still shows the old text. 

![image](https://user-images.githubusercontent.com/10515065/53377682-c23b0b00-395a-11e9-88ab-1ad6274f19f3.png)

here is an example with state logged and
```
 <Editor
            variant={VARIANT.SMALL}
            content={this.state.editorInput}
            onChange={content => this.editorChanged(content)}
          />
```

**Comment by tx4x** [comment] 2019-02-26 08:30
hi,
i am afraid i cant reproduce this. as soon i press save, it's in a lop of sending stuff to the backend.

**Comment by chrismclarke** [comment] 2019-02-26 09:41
I'm on chrome latest, video below:
http://recordit.co/FbSfCpxEKN

(expect text to clear after save operation completed, the state is updated to set editorInput as '', I manually delete at the end of the vid)

**Comment by tx4x** [comment] 2019-02-26 09:46
i see, thanks

**Comment by chrismclarke** [comment] 2019-02-26 09:52
I'm pretty sure it's at the editor level, I can see the editor is passed the new content props however this doesn't update the state. One workaround would be to add
```
 componentWillReceiveProps(next: IEditorProps) {
    this.setState({ content: next.content })
  }
```
to the Editor.ts file, however no idea if this is the best solution or not

**Comment by tx4x** [comment] 2019-02-27 07:54
sure, i believe you :-) 
anyway, i still can't really reproduce this since pressing 'save' will end up in a loop : 

![image](https://user-images.githubusercontent.com/1205100/53474374-3239b600-3a6d-11e9-88b3-88333a84d9ce.png)

**Comment by tx4x** [comment] 2019-02-27 08:04
can you try in src/components/Editor/Editor.tsx  ? : 

private contentChange = value => {
    this.setState({ content: value })
}

**Comment by tx4x** [comment] 2019-02-27 08:26
i've made changes regarding this in the last PR (sanitize), please try.

**Comment by chrismclarke** [comment] 2019-02-27 11:08
That's worrying, I don't get a loop! It just saves and then gets on with its life. Guess this requires some investigation too

**Comment by chrismclarke** [comment] 2019-02-27 11:36
PR merged, I still have the same issue but will just sit down properly one evening and fix. Let me know if you figure out why you get a saving loop while mine just saves correctly...

**Comment by BenGamma** [comment] 2019-07-17 12:43
closing since part of discussion module

**Closed by BenGamma** 2019-07-17 12:43 UTC
Labels: Mod: Discussions 💬, Priority: Low, Type:Bug🐛
