### ISSUE TITLE
[Enhancement] - Only allow signed in user to create how-to

### ISSUE THREAD

**Issue by chrismclarke** [OneArmyWorld/onearmy#463] opened 2019-05-02 20:06 UTC
**Describe the bug**
Currently anyone can create a how-to, need to limit this to only logged in users

**To Reproduce**
Log out, click on create how-to button or nav direct to create page

**Expected behavior**
Button doesn't appear for logged out user, page redirects or shows message when nav direct

child of #3

**Comment by BenGamma** [comment] 2019-05-06 10:54
duplicate of #457

**Closed by BenGamma** 2019-05-06 10:54 UTC
Labels: Frontend, Good first issue, Help wanted, Type:Enhancement
